### ISSUE TITLE
Could not build it in Mix project on OSX

### ISSUE THREAD

**Issue by developerworks** [tatsuya6502/recon_ex#2]
Deps:

``` elixir
defp deps do
  [{:recon_ex, "~> 0.9.1"}]
end
```

Build errors:

``` shell
Could not compile :recon, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)

== Compilation error on file lib/recon_lib.ex ==
** (CompileError) lib/recon_lib.ex:2: module :recon_lib is not loaded and could not be found

== Compilation error on file lib/recon_alloc.ex ==
** (CompileError) lib/recon_alloc.ex:2: module :recon_alloc is not loaded and could not be found

== Compilation error on file lib/recon_trace.ex ==
** (CompileError) lib/recon_trace.ex:2: module :recon_trace is not loaded and could not be found

== Compilation error on file lib/recon.ex ==
** (CompileError) lib/recon.ex:2: module :recon is not loaded and could not be found
==> recon_ex
could not compile dependency :recon_ex, "mix compile" failed. You can recompile this dependency with "mix deps.compile recon_ex", update it with "mix deps.update recon_ex" or clean it with "mix deps.clean recon_ex"
```

**Comment by nichochar** [comment]
Running into the same problem.
Elixir 1.3.4
OTP 18

**Comment by thecodeboss** [comment]
Ran into this same issue on Elixir 1.3.4, OTP 18.
Managed to fix it by doing a `mix deps.update recon`.
`mix.lock` change looks like:
```diff
-  "recon": {:hex, :recon, "2.3.2", "4444c879be323b1b133eec5241cb84bd3821ea194c740d75617e106be4744318", [:rebar3], [], "hexpm"},
+  "recon": {:hex, :recon, "2.3.4", "b406c2fccdeaa0d94e23b5e30ae3d635a2d461e363a5c9c6316897037cf050d2", [:rebar3], [], "hexpm"},
```
